version: "3.8"

services:
  backend:
    image: turbines-app
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    expose:
      - "9000"
    volumes:
      - .:/var/www/app
    networks:
      - app-network

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
